#!/usr/bin/env python3

import csv
import io
import sys
import urllib.request

url = "https://www.iana.org/assignments/tls-parameters/tls-parameters-4.csv"
out = open(sys.argv[1],"w")

out.write("// Code generated by go generate; DO NOT EDIT.\n\n")
out.write("package tls\n\n")
out.write("var cipherSuiteNames = map[int]string{\n")

url_open = urllib.request.urlopen(url)
rows = csv.DictReader(io.StringIO(url_open.read().decode('utf-8')))
for row in rows:
    if row['Description'].startswith('TLS_'):
        val = row['Value']
        out.write("\t{}: \"{}\",\n".format(val[0:4]+val[7:9], row['Description']))

out.write("}\n")
