name: Gofmt
on: [push, pull_request]
jobs:

  build:
    name: Gofmt check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14' ]
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Check gofmt
      uses: Jerome1337/gofmt-action@v1.0.4
      with:
        gofmt-path: './'
        gofmt-flags: -l -s
