name: Gofmt
on:
  push:
  pull_request:
  schedule:
    # Run every 12 hours, at the 15 minute mark. E.g.
    # 2020-11-29 00:15:00 UTC, 2020-11-29 12:15:00 UTC, 2020-11-30 00:15:00 UTC
    - cron:  '15 */12 * * *'
jobs:

  build:
    name: Gofmt check
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Check gofmt
      uses: Jerome1337/gofmt-action@v1.0.4
      with:
        gofmt-path: './'
        gofmt-flags: -l -s
