// Code generated by "stringer -type=InvalidASN1Reason -trimprefix=Reason"; DO NOT EDIT.

package x509

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReasonUnknown-0]
	_ = x[ReasonInvalidInteger-1]
	_ = x[ReasonMismatchedTag-2]
	_ = x[ReasonInvalidSequence-3]
}

const _InvalidASN1Reason_name = "UnknownInvalidIntegerMismatchedTagInvalidSequence"

var _InvalidASN1Reason_index = [...]uint8{0, 7, 21, 34, 49}

func (i InvalidASN1Reason) String() string {
	if i < 0 || i >= InvalidASN1Reason(len(_InvalidASN1Reason_index)-1) {
		return "InvalidASN1Reason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InvalidASN1Reason_name[_InvalidASN1Reason_index[i]:_InvalidASN1Reason_index[i+1]]
}
